apiVersion: v1
kind: Service
metadata:
  labels:
    app: mlservice
  name: mlservice
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mlservice
  type: LoadBalancer
status:
  loadBalancer: {}
